### ISSUE TITLE
Heslo uložené v čitelné podobě

### ISSUE THREAD

**Issue by N1kd0o** [sps-trutnov/projekt-4ep-pruvodce#12]
Pokud při registraci zadáš neshodující se hesla, registrace projde a heslo se uloží v čitelné podobě.
Na účet se následně nedá přihlásit.

![image](https://github.com/sps-trutnov/projekt-4ep-pruvodce/assets/81440885/7098f658-070a-4623-b07e-d8a9168e7ceb)
![image](https://github.com/sps-trutnov/projekt-4ep-pruvodce/assets/81440885/d9f8770b-a57b-4405-8475-4873d0e614ee)

**Comment by kukavlk** [comment]
opraveno

**Comment by kukavlk** [comment]
teď už opraveno
