### ISSUE TITLE
Datový model pro stravovací zařízení v okolí

### ISSUE THREAD

**Issue by AlesObr** [sps-trutnov/projekt-4ep-pruvodce#7]
Název
Adresa
Odkaz na menu
Popis
Další (?) @murtingg ?

**Comment by murtingg** [comment]
Kebaby v okolí si vezme na starost @Crelleess
Zítra pořeším ostatní zařízení (pizzerie, jídelny, kavárny), popřípadě rozdělím práci ještě Markovi M.

**Comment by AlesObr** [comment]
Slouží zejména pro vytvoření modelu v projektu ("programátorksy"), což se ještě nestalo.

**Comment by Joucker29** [comment]
Model domodelován
