### ISSUE TITLE
Opravit klíč v UserModel

### ISSUE THREAD

**Issue by AlesObr** [sps-trutnov/projekt-4ep-pruvodce#9]
udělat z hesla klíč v databázi je naprostý nesmysl. Nemůžeme zaručit unikátnost toho hesla v rámci celé databáze.
Jako ID se bude používat GUID (když bude dělat bordel nahradíme obyčejným intem)

**Comment by kukavlk** [comment]
Opraveno, misto toho tam je ID

**Comment by AlesObr** [comment]
Používá se obyčejný int místo GUID

**Comment by FireGamesCZ** [comment]
Jakou má pro nás výhodu GUID? Nestačilo by buď username, podle kterého stejně vyhledáváme a nebo prostě číselné ID?

**Comment by kukavlk** [comment]
Už tam je GUID, doufám, že už se tohle isue nebude dál otevírat
